Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions

In [1]:
class Employee:
    # Class variables to keep track of total employees and total salary
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Update class variables
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        return cls.total_salary / cls.employee_count if cls.employee_count > 0 else 0

    def display_info(self):
        return f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}"


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self, name, family, salary, department)


# Create instances of FulltimeEmployee and Employee classes
employee1 = FulltimeEmployee("Lokesh", "Cherukula", 80000, "IT")
employee2 = FulltimeEmployee("Goutham", "Kolli", 75000, "Finance")
employee3 = Employee("Ramesh", "kumar", 50000, "Sales")
employee4 = Employee("mani", "prakash", 60000, "HR")

# Display information of employees
print(employee1.display_info())
print(employee2.display_info())
print(employee3.display_info())
print(employee4.display_info())

# Calculate and print average salary and total employee count
print(f"\nAverage Salary: {int(Employee.average_salary())}")
print(f"Total Employees: {Employee.employee_count}")


Name: Lokesh, Family: Cherukula, Salary: 80000, Department: IT
Name: Goutham, Family: Kolli, Salary: 75000, Department: Finance
Name: Ramesh, Family: kumar, Salary: 50000, Department: Sales
Name: mani, Family: prakash, Salary: 60000, Department: HR

Average Salary: 66250
Total Employees: 4


Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [2]:
import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Step 2: Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Step 3: Replace the maximum value in each row by 0 (without using a loop)
# Get the indices of the maximum values in each row
max_indices = np.argmax(reshaped_array, axis=1)

# Create a copy of the array to modify
modified_array = reshaped_array.copy()

# Use advanced indexing to set the max values to 0
modified_array[np.arange(modified_array.shape[0]), max_indices] = 0

print("Original Reshaped Array:\n", reshaped_array)
print("\nModified Array with max in each row replaced by 0:\n", modified_array)


Original Reshaped Array:
 [[13.52835226  7.97655626 11.57175011 19.63017431 11.24044015]
 [15.90413068  2.06920907  6.14468123 14.32126463  4.92871866]
 [ 1.38144013 17.05893276  4.49408429 17.93902159 14.2999777 ]
 [ 6.90557567 14.81419518 16.7014991  10.94370134  8.09625197]]

Modified Array with max in each row replaced by 0:
 [[13.52835226  7.97655626 11.57175011  0.         11.24044015]
 [ 0.          2.06920907  6.14468123 14.32126463  4.92871866]
 [ 1.38144013 17.05893276  4.49408429  0.         14.2999777 ]
 [ 6.90557567 14.81419518  0.         10.94370134  8.09625197]]
